name: Run yapf

on:
  pull_request:
    types: [opened, reopened]

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run YAPF to test if python code is correctly formatted
      uses: AlexanderMelde/yapf-action@master
      with:
        args: --style .style.yapf --verbose --exclude '**/training/**'
